name: Deploy php 8.4

on:
  push:
    paths:
      - 'php-8.4/**'
    branches:
      - "master"

concurrency:
  group: php-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/vercel.yml
    secrets: inherit
    with:
      projectId: "prj_PLACEHOLDER_8_4"
      projectPath: "php-8.4"
